"""
Train the MediRoute urgency-tier classifier.

WHAT THIS MODEL IS
    A dispatch-priority router. Given administrative intake features it predicts
    which of four *operational* queues a request belongs in: emergency dispatch,
    urgent same-day, routine appointment, or pharmacy/self-care.

WHAT THIS MODEL IS NOT
    A diagnostic model. Its output vocabulary contains no medical condition. It
    is trained on SYNTHETIC data generated by the documented rule process below,
    plus label noise. It has not been clinically validated and must not be used
    to make a clinical decision. Where it is unsure it abstains to a human.

    Run:  npm run train
"""

import json
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn

SEED = 7
torch.manual_seed(SEED)
rng = np.random.default_rng(SEED)

OUT_DIR = Path(__file__).parent / "models"
OUT_DIR.mkdir(exist_ok=True)
MODEL_PATH = OUT_DIR / "urgency_mlp_v1.pt"
METRICS_PATH = OUT_DIR / "metrics.json"

# --------------------------------------------------------------------------
# Feature layout — MUST match FEATURE_ORDER in shared/enums.js, in this order.
# --------------------------------------------------------------------------
SYMPTOM_IDS = [
    "chest-pain", "breathing-difficulty", "trauma-bleeding", "unconscious",
    "poisoning-suspected", "pregnancy-related", "burn", "fracture-suspected",
    "high-fever", "abdominal-pain", "minor-injury", "routine-followup",
]
EXTRA = ["durationBucket", "ageBucket", "chronicFlag", "immobileFlag", "severitySelf", "hourOfDay"]
FEATURE_ORDER = SYMPTOM_IDS + EXTRA
FEATURE_DIM = len(FEATURE_ORDER)  # 18
TIERS = ["T1", "T2", "T3", "T4"]

# Acuity weight per tag. This is the labelling *process*, not a medical claim —
# it encodes how a dispatch desk would prioritise a queue.
TAG_ACUITY = {
    "unconscious": 10.0, "trauma-bleeding": 9.0, "poisoning-suspected": 9.0,
    "chest-pain": 8.2, "breathing-difficulty": 8.0, "pregnancy-related": 7.0,
    "burn": 6.0, "fracture-suspected": 5.0, "high-fever": 4.0,
    "abdominal-pain": 4.0, "minor-injury": 2.0, "routine-followup": 1.0,
}
# Sampling weights — routine traffic dominates real intake volume.
TAG_FREQ = np.array([
    0.06, 0.07, 0.05, 0.03, 0.02, 0.04,   # higher-acuity tags
    0.03, 0.07, 0.14, 0.13, 0.16, 0.20,   # lower-acuity tags
])
TAG_FREQ = TAG_FREQ / TAG_FREQ.sum()


def make_row():
    """Sample one synthetic intake and label it with the documented rule process."""
    n_tags = rng.choice([1, 2, 3], p=[0.62, 0.30, 0.08])
    tags = list(rng.choice(len(SYMPTOM_IDS), size=n_tags, replace=False, p=TAG_FREQ))

    duration_bucket = int(rng.choice(5, p=[0.30, 0.25, 0.20, 0.15, 0.10]))
    age_bucket = int(rng.choice(6, p=[0.08, 0.10, 0.30, 0.24, 0.18, 0.10]))
    chronic = int(rng.random() < (0.15 + 0.06 * age_bucket))
    immobile = int(rng.random() < 0.12)
    severity = int(rng.integers(1, 6))
    hour = int(rng.integers(0, 24))

    acuity = [TAG_ACUITY[SYMPTOM_IDS[t]] for t in tags]
    score = max(acuity) + 0.45 * (len(acuity) - 1)

    score += (severity - 3) * 0.85              # what the caller reports matters
    score += [1.0, 0.2, 0.0, 0.25, 0.7, 1.2][age_bucket]   # very young / very old
    score += 1.5 * immobile
    score += 0.6 * chronic
    if score < 7.0:                              # long-standing, non-critical -> less urgent
        score -= 0.42 * duration_bucket
    score += rng.normal(0, 0.7)                  # label noise -> genuine ambiguity

    tier = 0 if score >= 8.0 else 1 if score >= 5.5 else 2 if score >= 3.0 else 3

    x = np.zeros(FEATURE_DIM, dtype=np.float32)
    for t in tags:
        x[t] = 1.0
    x[12] = duration_bucket / 4.0
    x[13] = age_bucket / 5.0
    x[14] = chronic
    x[15] = immobile
    x[16] = severity / 5.0
    x[17] = hour / 23.0
    return x, tier


def make_dataset(n):
    xs, ys = zip(*(make_row() for _ in range(n)))
    return torch.tensor(np.array(xs)), torch.tensor(np.array(ys), dtype=torch.long)


class UrgencyMLP(nn.Module):
    def __init__(self, dim=FEATURE_DIM, n_classes=4):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(dim, 64), nn.ReLU(), nn.Dropout(0.2),
            nn.Linear(64, 32), nn.ReLU(), nn.Dropout(0.2),
            nn.Linear(32, n_classes),
        )

    def forward(self, x):
        return self.net(x)  # logits


def fit_temperature(logits, labels):
    """Temperature scaling. Raw softmax is overconfident, and our abstain gate is
    a confidence threshold — an uncalibrated threshold would abstain on the wrong
    cases. One scalar, fitted on held-out data."""
    log_t = torch.zeros(1, requires_grad=True)
    opt = torch.optim.LBFGS([log_t], lr=0.1, max_iter=60)
    nll = nn.CrossEntropyLoss()

    def closure():
        opt.zero_grad()
        loss = nll(logits / log_t.exp(), labels)
        loss.backward()
        return loss

    opt.step(closure)
    return float(log_t.exp().item())


def expected_calibration_error(probs, labels, bins=10):
    conf, pred = probs.max(dim=1)
    correct = pred.eq(labels).float()
    ece, n = 0.0, len(labels)
    edges = torch.linspace(0, 1, bins + 1)
    for lo, hi in zip(edges[:-1], edges[1:]):
        m = (conf > lo) & (conf <= hi)
        if m.sum() > 0:
            ece += (m.sum().item() / n) * abs(correct[m].mean().item() - conf[m].mean().item())
    return ece


def main():
    print(f"[train] generating synthetic data (seed={SEED})")
    x_tr, y_tr = make_dataset(8000)
    x_va, y_va = make_dataset(1500)
    x_te, y_te = make_dataset(1500)

    model = UrgencyMLP()
    opt = torch.optim.Adam(model.parameters(), lr=3e-3)
    loss_fn = nn.CrossEntropyLoss()

    print("[train] fitting 18 -> 64 -> 32 -> 4")
    for epoch in range(1, 41):
        model.train()
        perm = torch.randperm(len(x_tr))
        total = 0.0
        for i in range(0, len(x_tr), 128):
            idx = perm[i : i + 128]
            opt.zero_grad()
            loss = loss_fn(model(x_tr[idx]), y_tr[idx])
            loss.backward()
            opt.step()
            total += loss.item() * len(idx)
        if epoch % 10 == 0:
            model.eval()
            with torch.no_grad():
                acc = model(x_va).argmax(1).eq(y_va).float().mean().item()
            print(f"  epoch {epoch:>2}  loss {total / len(x_tr):.4f}  val_acc {acc:.3f}")

    model.eval()
    with torch.no_grad():
        va_logits = model(x_va)
        temperature = fit_temperature(va_logits, y_va)

        te_logits = model(x_te)
        raw_probs = te_logits.softmax(1)
        cal_probs = (te_logits / temperature).softmax(1)
        pred = cal_probs.argmax(1)
        acc = pred.eq(y_te).float().mean().item()

        # How often does the abstain gate fire, and is abstaining actually useful?
        top2 = cal_probs.topk(2, dim=1).values
        abstain = (top2[:, 0] < 0.65) | ((top2[:, 0] - top2[:, 1]) < 0.15)
        acc_conf = pred[~abstain].eq(y_te[~abstain]).float().mean().item()
        acc_abst = pred[abstain].eq(y_te[abstain]).float().mean().item() if abstain.any() else float("nan")

        cm = torch.zeros(4, 4, dtype=torch.int32)
        for t, p in zip(y_te, pred):
            cm[t, p] += 1

        # Safety-relevant: a true T1 predicted as T3/T4 is the costly error.
        t1_recall = (cm[0, 0] / max(int(cm[0].sum()), 1)).item()
        t1_underrouted = int(cm[0, 2] + cm[0, 3])

    metrics = {
        "model_version": "urgency-mlp-v1",
        "feature_dim": FEATURE_DIM,
        "train_rows": len(x_tr),
        "test_accuracy": round(acc, 4),
        "accuracy_on_confident": round(acc_conf, 4),
        "accuracy_on_abstained": round(acc_abst, 4),
        "abstain_rate": round(abstain.float().mean().item(), 4),
        "temperature": round(temperature, 4),
        "ece_raw": round(expected_calibration_error(raw_probs, y_te), 4),
        "ece_calibrated": round(expected_calibration_error(cal_probs, y_te), 4),
        "t1_recall": round(t1_recall, 4),
        "t1_underrouted_to_t3_t4": t1_underrouted,
        "confusion_matrix": cm.tolist(),
        "tiers": TIERS,
        "note": "Synthetic data from a documented rule process. Dispatch priority only, not a diagnosis.",
    }

    torch.save(
        {"state_dict": model.state_dict(), "temperature": temperature,
         "feature_order": FEATURE_ORDER, "metrics": metrics},
        MODEL_PATH,
    )
    METRICS_PATH.write_text(json.dumps(metrics, indent=2))

    print(f"\n[train] test accuracy        {acc:.3f}")
    print(f"[train] confident subset     {acc_conf:.3f}  (abstain rate {abstain.float().mean():.1%})")
    print(f"[train] abstained subset     {acc_abst:.3f}  <- these go to a human, and rightly so")
    print(f"[train] ECE  {metrics['ece_raw']:.4f} -> {metrics['ece_calibrated']:.4f} after T={temperature:.3f}")
    print(f"[train] T1 recall {t1_recall:.3f}   T1 under-routed to T3/T4: {t1_underrouted}")
    print(f"[train] confusion matrix (rows=true {TIERS}):")
    for r, row in zip(TIERS, cm.tolist()):
        print(f"          {r} {row}")
    print(f"[train] saved -> {MODEL_PATH}")


if __name__ == "__main__":
    main()
